# Font
font_family JetBrainsMono Nerd Font
font_size 18.0

# Transparency (0 = fully transparent, 1 = opaque)
background_opacity 0.5

# Optional but recommended on Wayland/X11
dynamic_background_opacity yes

# Font
font_family JetBrainsMono Nerd Font
font_size 18

# Transparency
background_opacity 0.4

# Main colors
foreground #c8d3f5
background #1b1d2b

# Tokyo Night Storm ANSI palette
color0  #1b1d2b
color1  #ff757f
color2  #c3e88d
color3  #ffc777
color4  #82aaff
color5  #c099ff
color6  #86e1fc
color7  #828bb8

color8  #444a73
color9  #ff8d94
color10 #c7fb6d
color11 #ffd8ab
color12 #9ab8ff
color13 #caabff
color14 #b2ebff
color15 #c8d3f5

# Make bold text not automatically become bright colors
bold_text_in_bright_colors no

# Cursor
cursor #c8d3f5
cursor_text_color #1b1d2b

# Selection
selection_foreground #000000
selection_background #e3c401

# URL color
url_color #e3c401

# Disable audio bell
enable_audio_bell no

disable_ligatures never
text_composition_strategy legacy

map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+0 change_font_size all 0

scrollback_lines 100000
