# Font
font_family JetBrainsMono Nerd Font
font_size 18.0

# Transparency (0 = fully transparent, 1 = opaque)
background_opacity 0.5

# Optional but recommended on Wayland/X11
dynamic_background_opacity yes

# Font
font_family JetBrainsMono Nerd Font
font_size 18

# Transparency
background_opacity 0.5

# Main colors
foreground #ffffff
background #000000

# Normal colors
color0  #242424
color1  #f62b5a
color2  #47b413
color3  #e3c401
color4  #24acd4
color5  #f2affd
color6  #13c299
color7  #e6e6e6

# Bright colors
color8  #616161
color9  #ff4d51
color10 #35d450
color11 #e9e836
color12 #5dc5f8
color13 #feabf2
color14 #24dfc4
color15 #ffffff

# Make bold text not automatically become bright colors
bold_text_in_bright_colors no

# Cursor
cursor #ffffff
cursor_text_color #000000

# Selection
selection_foreground #000000
selection_background #e3c401

# URL color
url_color #e3c401

# Disable audio bell
enable_audio_bell no

disable_ligatures never
text_composition_strategy legacy

map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+0 change_font_size all 0
