#!/bin/bash

if [ $# -gt 2 ]; then
	exit 1
fi

if [ $1 -eq '-i' ]; then
	cd /home/mahad/Pictures/OS/tmp && cp og.png hyprlock-tmp.png && hyprlock
	exit 0
fi


mkdir -p /home/mahad/Pictures/OS/tmp/ && cd /home/mahad/Pictures/OS/tmp/ && grim -l 0 hyprlock-tmp.png && hyprlock
