#Colour format: 0xAARRGGBB

background {
	path = $HOME/Pictures/OS/lock.webp
	blur_passes = 1
	blur_size = 7
}

#Time
label {
	text = cmd[update:1000] date +'%H:%M'
	color = 0xBBEEEEFF
	font_family = JetBrainsMono Nerd Font
	font_size = 130
	halign = center
	valign = center
	position = 0, 550
}

#Date
label {
	text = cmd[update:60000] date +'%A, %d %B %Y'
	color = 0xAAEEEEFF
	font_family = JetBrainsMono Nerd Font
	font_size = 32
	halign = center
	valign = center
	position = 0, 700
}

input-field {
	size = 300, 60
	position = 0, -700
	halign = center
	valign = center
	font_family = JetBrainsMono Nerd Font
	placeholder_text = 
	dots_spacing = 0.6
	dots_size = 0.1
	inner_color = 0x55EEEEFF
	outer_color = 0x00000000
}
