source = ~/.config/hypr/hidpi.conf

monitor=eDP-1,preferred,auto,1
monitor=DP-2,preferred,2880x0,0.5

#Start up waybar, notifs and wallpaper and lock screen (auto login)
exec-once = waybar
exec-once = mako

#These are dedicated wallpaper managers - I don't use them, I just driectly overwrite
#the default wallpapers at /usr/share/hypr/

#exec-once = hyprpaper
#exec-once = swww-daemon
#exec-once = swww img ~/Pictures/OS/wallpaper.webp --transition-type none

exec-once = hyprctl setcursor default 24 && sleep 0.6 && hyprlock
exec-once = systemctl --user start hypridle.service

# Run at cliphist startup
exec-once = sh -c 'wl-paste --watch cliphist store >/dev/null 2>&1 &'

#Startup playerctl daemon
exec-once = playerctld daemon

#Binds
bind = SUPER, ESCAPE, exit,
bind = SUPER, RETURN, exec, foot
bind = SUPER, SPACE, exec, fuzzel
bind = SUPER, L, exec, hyprlock

bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d

bind = ALT CTRL, left, resizeactive, -20 0
bind = ALT CTRL, right, resizeactive, 20 0
bind = ALT CTRL, up, resizeactive, 0 -20
bind = ALT CTRL, down, resizeactive, 0 20

# Clipboard menu via cliphist
bind = SUPER, V, exec, sh -c 'cliphist list | fuzzel --dmenu --width 60 | cliphist decode | wl-copy'

# Screenshots
bind = , Print, exec, grim -g "$(slurp)" - | swappy -f -

# Volume
bind = , F1, exec, pamixer -t
bind = , F2, exec, pamixer -d 2
bind = , F3, exec, pamixer -i 2

# Mic mute
bind = , F4, exec, pamixer --default-source -t

# Brightness
bind = , F5, exec, brightnessctl set 5%-
bind = , F6, exec, brightnessctl set 5%+

# Toggle waybar
bind = , F9, exec, bash -c "pgrep -x waybar >/dev/null && pkill -x waybar || waybar >/dev/null 2>&1 &"

bind = SUPER, Q, killactive,
bind = , F11, fullscreen, 0
#Fake full screen - just maximises the active window
bind = SHIFT, F11, exec, hyprctl dispatch fullscreen 1

#Copilot button launches zen-browser
bind = SUPER SHIFT, code:201, exec, zen-browser

#Windows-like task manager (ctrl + shift + esc opens btop)
bind = CTRL SHIFT, ESCAPE, exec, foot -e btop

#Workspaces
bind = CTRL SUPER, left, workspace, -1
bind = CTRL SUPER, right, workspace, +1
bind = CTRL SUPER ALT, right, movetoworkspace, +1
bind = CTRL SUPER ALT, left, movetoworkspace, -1

#Windows
bind = SUPER, F, togglefloating
bindm = SUPER SHIFT, mouse:272, resizewindow
bindm = SUPER, mouse:272, movewindow

general {
	border_size = 2
	col.active_border = 0xff3a4750
}

#decorations
decoration {
	active_opacity = 0.87
	inactive_opacity = 0.8

	shadow {
		enabled = false
	}

	rounding = 20

	blur {
		brightness = 1
		enabled = true
		size = 13
		passes = 2
		contrast = 1.15
		noise = 0.1

		new_optimizations = true
		ignore_opacity = false
		xray = true
	}
}

#Modify animations
animations {
	enabled = yes
	animation = windows, 1, 3, default, slide
	animation = windowsOut, 1, 3, default, slide
	animation = border, 1, 3, default
	animation = fade, 1, 3, default
	animation = workspaces, 1, 5, default, slide
}

#Scrolling
input {
	natural_scroll = 1
	touchpad {
		natural_scroll = 1
	}

	kb_file = ~/.config/hypr/gb.xkb
}

#Set dark mode on most apps
env = GTK_THEME,Adwaita:dark
env = GTK_THEME_VARIANT, dark
env = QT_STYLE_OVERRIDE,Adwaita-Dark
env = QT_QPA_PLATFORMTHEME,qt5ct

device {
	name = elan06fa:00-04f3:3280-touchpad
	sensitivity = 0.5
}
